/**
 * StyleSync API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressResource } from './addressResource';


export interface UserResource { 
    id?: string;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    address?: AddressResource;
    lastModifiedUtc?: string | null;
    createdTimeUtc?: string | null;
}

